### ISSUE TITLE
部分network图标显示异常

### ISSUE THREAD

**Issue by LEAFERx** [revir/need-more-share2#3]
![image 1](https://user-images.githubusercontent.com/20595509/31051464-b454469e-a69b-11e7-8d61-b552e9fdd287.png)
如图所示
目前涉及到的icon有：
Mailto,Delicious,Tapiture,StumbleUpon,Slashdot,Technorati,Posterous,GoogleBookmarks,Newsvine,Pingfm,Friendfeed,Vkontakte,Odnoklassniki,Mailru
![image 3](https://user-images.githubusercontent.com/20595509/31051472-e8f6ba1c-a69b-11e7-89d4-e791cfcbab9f.png)

**Comment by LEAFERx** [comment]
在default下同样不正常
![image 4](https://user-images.githubusercontent.com/20595509/31051495-67fc4430-a69c-11e7-9d6d-5685222fcb8c.png)

**Comment by ivan-nginx** [comment]
Affermative. `social` font was cutted out from this fork. Instead of this in `fontello-embedded.css` used `fontello` wich is not exist in distr dir:

https://github.com/revir/need-more-share2/blob/8662c4b342bccd9aff981bf068a92ee5cee9b434/dist/fontello-embedded.css#L3-L5

**Comment by revir** [comment]
抱歉， 这么久了才更新。
现在已部分修复了这个问题， font 文件已加入了 dist， 部分图标已修复。
但是有极少部分网站我找不的相应的图标，所以我从库里去除了这些网站，包括： tapiture， slashdot， technorati， googlebookmarks， newsvine， pingfm， mailru。
如果你可以提供这些网站的图标，欢迎提交重开 issue.
