### ISSUE TITLE
微信分享加载不出来

### ISSUE THREAD

**Issue by leviding** [revir/need-more-share2#4]
设置了一些分享，但是只有微信加载不出来。如下图：
![image](https://user-images.githubusercontent.com/26959437/31434817-167a1594-aeb0-11e7-8d44-55ed5cfb2f1e.png)

**Comment by leviding** [comment]
在您的 nodebb.tech 网站上，微信分享也加载不出来
![image](https://user-images.githubusercontent.com/26959437/31434916-72ace42c-aeb0-11e7-8083-b857bd19fbe4.png)

**Comment by Aqua-Dream** [comment]
同样的问题。

**Comment by Aqua-Dream** [comment]
作者几天没回复，只好自己去看了下，应该是原来生成二维码的api停止服务了，可以在这里寻找替换方案：http://www.inlojv.com/5455.html 
修改`themes\next\source\lib\needsharebutton\needsharebutton.js`，
把
```js
var imgSrc = "https://api.qinco.me/api/qr?size=400&content=" + encodeURIComponent(myoptions.url);
```
修改为
```js
var imgSrc = "https://pan.baidu.com/share/qrcode?w=400&h=400&url=" + encodeURIComponent(myoptions.url);
```
即可。

**Comment by Aqua-Dream** [comment]
抱歉，我误解了那个网站的功能，实质为生成网址的二维码，而非微信分享功能，所以这样的替代方案是不合适的。
我会继续寻找解决方案，目前在看这个：http://qydev.weixin.qq.com/wiki/index.php?title=%E5%BE%AE%E4%BF%A1JS%E6%8E%A5%E5%8F%A3

**Comment by leviding** [comment]
嗯，这个 API 确实是生成一个本网址的图片，本 repo 作者也是让这生成一个图片，如果这生成图片的话，我估计就是生成一个本网址的二维码。因为分享到微信有分享到朋友圈和朋友两个选项，不知是否有相应的 API。

**Comment by Aqua-Dream** [comment]
现在微信开发平台认证就要300元，应该没得公用接口了，估计最好的效果也只能这样了ei~

**Comment by leviding** [comment]
@Aqua-Dream 感谢分享啦

**Comment by wangweiX** [comment]
![wx20171116-194101](https://user-images.githubusercontent.com/7995377/32889581-69f34f48-cb06-11e7-81d1-66963faa4807.png)
![wx20171116-193845](https://user-images.githubusercontent.com/7995377/32889582-6a27737c-cb06-11e7-9bf0-100be2e14032.png)

**Comment by stanleyliu918** [comment]
![image](https://user-images.githubusercontent.com/24445129/33060566-a01d4ab2-ced3-11e7-870c-17f8e1531cb1.png)
同样的问题，期待解决。

**Comment by caili-zhang** [comment]
网站开发新手， 怎么样才能不用按按钮，默认显示出一排呢

**Comment by franklee628** [comment]
@stanleyliu918 看下上面 Aqua-Dream 的回复。
@caili-zhang 如果不想修改，可以考虑AddtoAny，国内各大SNS都有。

**Comment by darrenliuwei** [comment]
我也遇到了微信分享加载不出来，同时也希望能将图标在一排显示，这样读者就可以少一个点击的步骤。

**Comment by ghost** [comment]
我也加载不出来微信分享的图片

**Comment by markey92** [comment]
@Aqua-Dream 不知道原先作者生成二维码的api效果是怎么样，现在直接换另一个生成二维码的api就可以了。

**Comment by markey92** [comment]
@stormxing  可以按照 @Aqua-Dream 的方法，换一个生成二维码的api试试，我用的是http://api.qrserver.com/v1/create-qr-code/?size=150x150&data=123

**Comment by CatherineLiyuankun** [comment]
可以看这个PR： https://github.com/iissnan/hexo-theme-next/pull/1976/files
source\lib\needsharebutton\needsharebutton.js

```javascript
var imgSrc = "https://api.qinco.me/api/qr?size=400&content=" + encodeURIComponent(myoptions.url);
```
改为
```javascript
var imgSrc = "http://tool.oschina.net/action/qrcode/generate?output=image/png&error=L&type=0&margin=2&size=4&data=" + encodeURIComponent(myoptions.url);

**Comment by darrenliuwei** [comment]
@CatherineLiyuankun 试了下，真的可以！太感谢了！谢谢大佬！终于解决了这个问题！

**Comment by CatherineLiyuankun** [comment]
@darrenliuwei 
不谢，我也是搭建博客的时候刚好遇到了这个问题，其他的我遇到的问题我写在[博客](https://blog.csdn.net/muzilanlan/article/details/81542917)里了，互相交流，还没写完，也还没搭建完。你可以参考我的[hexo主题](https://github.com/CatherineLiyuankun/Hexo-theme-zilan)。我的博客地址：https://catherineliyuankun.github.io/

**Comment by revir** [comment]
抱歉大家，这么久了我才看到这个issue的讨论。
根据上面大家的上面的交流，目前使用 oschina 和 qrserver 提供的 api 可以解决。
我这里使用的是 qrserver, 但我不知道能持续多久，而且我的网站(v2mm) 在微信上的分享早就被禁了。。。
此issue先保持开着，如果还有人遇到这个问题，可以继续在此回复。

**Comment by revir** [comment]
抱歉我先关闭这个issue，因为目前使用 qrserver 提供的服务很稳定。

**Comment by ghost** [comment]
用qrserver生成二维码，但是用手机扫是空白页面啊
