### ISSUE TITLE
可以默认显示分享图标吗？

### ISSUE THREAD

**Issue by ghost** [revir/need-more-share2#8]
可以默认显示分享图标吗？让分享图标在文章底部一排显示，而不是点击分享，然后弹出图标。

**Comment by revir** [comment]
Thanks.
这个 issue 已经很久了，  也许你再也用不到。不过我最近自己也碰到了这个问题，所以顺手改了一下，现在支持默认显示分享图标了。

如果需要默认就展示分享图标， 只需要加上 need-share-panel 的 class. 参考 Demo 页面.
